find_path(LIBPTHREAD_INCLUDE_DIR NAMES pthread.h HINTS "${DepsPath}/include")

set(PTHREAD_LIBS pthreadVC3 pthreadVCE3 pthreadVSE3)
set(PTHREAD_LIBS_DEBUG pthreadVC3d pthreadVCE3d pthreadVSE3d)

FOREACH(LIB ${PTHREAD_LIBS})
        FIND_LIBRARY(FOUND_LIB_${LIB} ${LIB} PATHS "${DepsPath}/bin")
        LIST(APPEND PTHREAD_REL_LIBS ${FOUND_LIB_${LIB}})
ENDFOREACH(LIB)

FOREACH(LIB ${PTHREAD_LIBS_DEBUG})
        FIND_LIBRARY(FOUND_DBG_LIB_${LIB} ${LIB} PATHS "${DepsPath}/bin/debug")
        LIST(APPEND PTHREAD_DBG_LIBS ${FOUND_DBG_LIB_${LIB}})
ENDFOREACH(LIB)

if(PTHREAD_DBG_LIBS AND PTHREAD_REL_LIBS)
        set(LIBPTHREAD_INCLUDE_DIRS ${LIBPTHREAD_INCLUDE_DIR})
        set(LIBPTHREAD_LIBRARIES ${PTHREAD_REL_LIBS})
        set(LIBPTHREAD_DEBUG_LIBRARIES ${PTHREAD_DBG_LIBS})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(pthread DEFAULT_MSG LIBPTHREAD_LIBRARIES LIBPTHREAD_DEBUG_LIBRARIES LIBPTHREAD_INCLUDE_DIRS)
mark_as_advanced(LIBPTHREAD_INCLUDE_DIRS LIBPTHREAD_DEBUG_LIBRARIES LIBPTHREAD_LIBRARIES)
